#!/bin/bash
# Relevance test script - runs core queries and prints top 3 per entity type
# Usage: ./scripts/test-relevance.sh [API_URL]
# Default: http://localhost:3001

API_URL="${1:-http://localhost:3001}"

# Core queries from docs/relevance-notes.md
QUERIES=(
  "pre-seed AI investors US"
  "seed fintech nordics founder"
  "CEO fintech"
  "climate supply chain startups"
  "fundraising workshop"
  "partner venture fund europe"
  "machine learnin climate"
  "starlink"
  "tesla"
)

echo "## Observed results (local, $(date +%Y-%m-%d))"
echo ""
echo "API: $API_URL"
echo ""

for query in "${QUERIES[@]}"; do
  echo "### Query: \`$query\`"
  echo ""

  # URL encode the query
  encoded_query=$(printf '%s' "$query" | jq -sRr @uri)

  # Fetch results
  response=$(curl -s "$API_URL/search?q=$encoded_query")

  if [ $? -ne 0 ] || [ -z "$response" ]; then
    echo "Error: Failed to fetch results"
    echo ""
    continue
  fi

  # Extract top 3 for each entity type
  for type in investors startups people events; do
    names=$(echo "$response" | jq -r ".$type[:3] | map(.name) | join(\", \")")
    total=$(echo "$response" | jq -r ".meta.totalByType.$type")

    if [ "$names" = "" ] || [ "$names" = "null" ]; then
      echo "- ${type^}: (none)"
    else
      echo "- ${type^} (${total}): $names"
    fi
  done

  echo ""
  echo "Notes: "
  echo ""
done

echo "---"
echo "Generated by scripts/test-relevance.sh"
